Updated post install, postuninstall, preuninstall and start-stop-status script. Added more validation, changed to synology official ENV variables and more

diff --git a/scripts/postuninst b/scripts/postuninst
--- a/scripts/postuninst
+++ b/scripts/postuninst
@@ -1,3 +1,34 @@
 #!/bin/sh
 
+AIRCONNECT_USER="$(echo ${SYNOPKG_PKGNAME} | awk {'print tolower($_)'})"
+LOG="/var/log/${AIRCONNECT_USER}.log"
+if [ ! -e "${LOG}" ]; then
+    touch ${LOG}
+fi
+echo "#### Start postuninst...####" >>$LOG
+echo "$(date +%Y-%m-%d:%H:%M:%S)" >>$LOG
+echo "" >>$LOG
+# Determine folder before deleting user
+AIRCONNECT_HOME="$(synouser --get ${AIRCONNECT_USER} | grep "User Dir" | awk -F[ '{print $2}' | awk -F] '{print $1}')"
+
+# Remove airconnect user if existing
+if ! synouser --get ${AIRCONNECT_USER} >/dev/null 2>&1; then
+    # create user with random password
+    echo "[$(date +'%T')] ${AIRCONNECT_USER} user not found - nothing deleted" >>$LOG
+else
+    echo "[$(date +'%T')] User ${AIRCONNECT_USER} found - deleting it" >>$LOG
+    synouser --del ${AIRCONNECT_USER}
+    sleep 3
+fi
+
+# Sanity check user had valid folder
+if [ -e "${AIRCONNECT_HOME}" ]; then
+    echo "[$(date +'%T')] ${AIRCONNECT_USER} user folder '${AIRCONNECT_HOME}' found - deleting it" >>$LOG
+    rm -r ${AIRCONNECT_HOME}
+else
+    echo "[$(date +'%T')] ${AIRCONNECT_USER} user folder '${AIRCONNECT_HOME}' not found - nothing deleted" >>$LOG
+fi
+
+echo "[$(date +'%T')] postuninst done" >>$LOG
+
 exit 0
diff --git a/scripts/start-stop-status b/scripts/start-stop-status
--- a/scripts/start-stop-status
+++ b/scripts/start-stop-status
@@ -2,31 +2,43 @@
 
 set -eu
 
-AIRCONNECT_DIR="/var/packages/AirConnect/target"
+AIRCONNECT_USER="$(echo ${SYNOPKG_PKGNAME} | awk {'print tolower($_)'})"
+CONFIG_UPNP_FILE="${SYNOPKG_PKGDEST}/config.xml"
+CONFIG_CAST_FILE="${SYNOPKG_PKGDEST}/config-cast.xml"
 
-CONFIG_UPNP_FILE="/volume1/development/workspace/AirConnect-Synology/dist/config.xml"
-CONFIG_CAST_FILE="/volume1/development/workspace/AirConnect-Synology/dist/config-cast.xml"
+LOG="/var/log/${AIRCONNECT_USER}.log"
+# Delete Log if older than 1 day
+find ${LOG} -mtime +1 -type f -delete >/dev/null 2>&1
+if [ -e "${LOG}" ]; then
+    chown ${AIRCONNECT_USER}:users ${LOG}
+else
+    touch ${LOG}
+    chown ${AIRCONNECT_USER}:users ${LOG}
+fi
 
-logfile="/tmp/airconnect.log"
-
-start_airconnect_on_ip ()
-{
+start_airconnect_on_ip() {
     ip="$1"
     port=49154
-    {
-        echo "[$(date +'%T')] Starting airupnp on ${ip}:${port}"
-    } >> ${logfile}
-    su airconnect -s /bin/sh -c "${AIRCONNECT_DIR}/airupnp -b ${ip}:${port} -x \"${CONFIG_UPNP_FILE}\" -z -f ${logfile}" >> ${logfile} 2>&1
+    if [ ! -z "${port}" ]; then
+        if netstat -tlpn | grep :${port}; then
+            echo "[$(date +'%T')] Your selected port ${port} is already in use." >>$LOG
+            echo "[$(date +'%T')] Please check what is running on the port and try again." >>$LOG
+            echo "[$(date +'%T')] Port ${port} already in use. Please check what is running on the port and try again." >>$SYNOPKG_TEMP_LOGFILE
+            exit 1
+        fi
+    fi
+    echo "[$(date +'%T')] Starting airupnp on ${ip}:${port}" >>$LOG
+    su airconnect -s /bin/sh -c "${SYNOPKG_PKGDEST}/airupnp -b ${ip}:${port} -l 1000:2000 -x \"${CONFIG_UPNP_FILE}\" -z -f ${LOG} -d all=info -d main=info" >>${LOG} 2>&1
 
+    echo "[$(date +'%T')] Starting aircast on ${ip}" >>$LOG
+    su airconnect -s /bin/sh -c "${SYNOPKG_PKGDEST}/aircast -b ${ip} -l 1000:2000 -x \"${CONFIG_CAST_FILE}\" -z -f ${LOG} -d all=info -d main=info" >>${LOG} 2>&1
 
-    {
-        echo "[$(date +'%T')] Starting aircast on ${ip}"
-    } >> ${logfile}
-    su airconnect -s /bin/sh -c "${AIRCONNECT_DIR}/aircast -b ${ip} -x \"${CONFIG_CAST_FILE}\" -z -f ${logfile}" >> ${logfile} 2>&1
-
+    # search for 10 seconds "adding renderer" in the logfile to check if speakers are found, if not return 1 rom the function
     cnt=0
-    while [ $cnt -lt 5 ]; do
-        if grep -q "adding renderer" ${logfile}; then
+    echo "[$(date +'%T')] Searching if renderer were added (for 10 seconds)..." >>$LOG
+    while [ $cnt -lt 10 ]; do
+        if grep -q "adding renderer" ${LOG}; then
+            echo "[$(date +'%T')] At least one renderer successfully discovered!" >>$LOG
             return 0
         fi
         cnt=$((cnt + 1))
@@ -35,22 +47,18 @@ start_airconnect_on_ip ()
     return 1
 }
 
-start_airconnect ()
-{
-    rm -f "${logfile}"
-    touch "${logfile}"
-    chown airconnect:users "${logfile}"
-
+start_airconnect() {
     # If you want to start the airconnect processes on a specific IP please uncomment the following lines
     # and set your own local IP address:
     #
     # start_airconnect_on_ip "1.2.3.4" || true
     # return 0
 
-    interfaces=$(ifconfig -a | grep 'Ethernet' -A 1 | grep -E 'inet (addr:)?(192\.168\.|10\.|172\.(1[6-9]|2[0-9]|3[01])\.)' -B 1 | grep 'Ethernet' | grep -v "lbr0" | grep -v "docker" | cut -d ' ' -f 1)
+    interfaces=$(/sbin/ifconfig -a | grep 'Ethernet' -A 1 | grep -E 'inet (addr:)?(192\.168\.|10\.|172\.(1[6-9]|2[0-9]|3[01])\.)' -B 1 | grep 'Ethernet' | grep -v "lbr0" | grep -v "docker" | cut -d ' ' -f 1)
 
     if [ -z "$interfaces" ]; then
-        echo "Failed to get local Ethernet interfaces" > "${SYNOPKG_TEMP_LOGFILE}"
+        echo "[$(date +'%T')] Failed to get local Ethernet interfaces" >>$LOG
+        echo "[$(date +'%T')] Failed to get local Ethernet interfaces" >>$SYNOPKG_TEMP_LOGFILE
         exit 1
     fi
 
@@ -58,28 +66,29 @@ start_airconnect ()
     interfaces="lbr0 $interfaces"
 
     for interface in $interfaces; do
-        ip=$(/sbin/ifconfig "$interface" 2> /dev/null | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')
+        ip=$(/sbin/ifconfig "$interface" 2>/dev/null | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')
         if [ -n "$ip" ]; then
             if start_airconnect_on_ip "$ip"; then
+                echo "[$(date +'%T')] AirConnect successfully started on ip \"${ip}\"!" >>$LOG
                 return 0
             else
+                echo "[$(date +'%T')] Failed to start AirConnect on ip \"${ip}\", stopping it..." >>$LOG
+                echo "[$(date +'%T')] Failed to start AirConnect on ip \"${ip}\", stopping it..." >>$SYNOPKG_TEMP_LOGFILE
                 stop_airconnect
             fi
         fi
     done
-
-    echo "Failed to start AirConnect on any of the local interfaces, please make sure you have at least one UPnP/Sonos/Chromecast device on your network" > "${SYNOPKG_TEMP_LOGFILE}"
+    echo "[$(date +'%T')] Failed to start AirConnect on any of the local interfaces, please make sure you have at least one UPnP/Sonos/Chromecast device on your network" >>$LOG
+    echo "[$(date +'%T')] Failed to start AirConnect on any of the local interfaces, please make sure you have at least one UPnP/Sonos/Chromecast device on your network" >>$SYNOPKG_TEMP_LOGFILE
     exit 1
 }
 
-stop_airconnect ()
-{
+stop_airconnect() {
     killall -16 airupnp
     killall -16 aircast
 }
 
-airconnect_status ()
-{
+airconnect_status() {
     # Check if ps has ax options
     if ps ax >/dev/null 2>&1; then
         # shellcheck disable=SC2009
@@ -97,31 +106,30 @@ airconnect_status ()
 }
 
 case $1 in
-    start)
-        echo Starting AirConnect ...
-        start_airconnect
-        exit $?
-        ;;
-    stop)
-        echo Stopping AirConnect ...
-        stop_airconnect
-        exit $?
-        ;;
-    status)
-        if airconnect_status
-        then
-            echo AirConnect is running
-            exit 0
-        else
-            echo AirConnect is not running
-            exit 1
-        fi
-        ;;
-    log)
-        echo "${logfile}"
+start)
+    echo "[$(date +'%T')] Starting AirConnect ..." >>$LOG
+    start_airconnect
+    exit $?
+    ;;
+stop)
+    echo "[$(date +'%T')] Stopping AirConnect ..." >>$LOG
+    stop_airconnect
+    exit $?
+    ;;
+status)
+    if airconnect_status; then
+        echo "[$(date +'%T')] AirConnect is running"
         exit 0
-        ;;
-    *)
+    else
+        echo "[$(date +'%T')] AirConnect is not running"
         exit 1
-        ;;
+    fi
+    ;;
+log)
+    echo "${LOG}"
+    exit 0
+    ;;
+*)
+    exit 1
+    ;;
 esac
